### ISSUE TITLE
Fix layout form

### ISSUE THREAD

**Issue by rijkerd** [CodeTanzania/ewea-web#111]
**Describe the bug**
Form dropdown elements not displaying any values

**Expected behaviour**
The dropdown should be displaying the value when clicked.

**Screenshots**
<img width="641" alt="Screenshot 2019-12-03 at 14 55 27" src="https://user-images.githubusercontent.com/18520338/70049687-4d2ded80-15de-11ea-816a-5ed3143104b2.png">

**Desktop:**
 - OS: MacOS Mojave 10.14.5
 - Browser: chrome 78

**Comment by BenMaruchu** [comment]
@rijkerd was this issue fixed? .. why is it closed?

**Comment by rijkerd** [comment]
@BenMaruchu Yes It was fixed. We tested submitting the form

**Comment by BenMaruchu** [comment]
@rijkerd  I was talking about layout Landline/Other number is not right

**Comment by navish** [comment]
Closed in #202
