### ISSUE TITLE
Fix pagination on event types settings page

### ISSUE THREAD

**Issue by navish** [CodeTanzania/ewea-web#201]
**Describe the bug**
An error is thrown when you click on the pagination buttons on event types page.

**Expected behavior**
Clicking on the pagination button should open the next page on the list.

**Screenshots**
![bug-eventtypes](https://user-images.githubusercontent.com/8484784/73925392-0bbc0600-48df-11ea-990c-a1733f48ac66.png)

**Desktop (please complete the following information):**
 - Ubuntu 18
 - Chrome
 -  v78.0.3904.108

**Comment by BenMaruchu** [comment]
This was a seed data issues. resolved by seeding data on a new database
