### ISSUE TITLE
Should improve the order of menu

### ISSUE THREAD

**Issue by lykmapipo** [CodeTanzania/ewea-web#28]
![Screenshot from 2019-09-27 15-26-53](https://user-images.githubusercontent.com/1610857/65769051-4fd21980-e13b-11e9-85c4-9e80ba130a09.png)

**1st Row:**
Issued Alerts, Action Taken, Action Catalog

**2nd Row:**
Focal People, Agencies, Roles

**3rd Row:**
AlertTypes, Geographical Features, Dashboards

**Comment by navish** [comment]
Closed in #33
