### ISSUE TITLE
Should allow recording alert is simplified form

### ISSUE THREAD

**Issue by lykmapipo** [CodeTanzania/ewea-web#3]
**Accepted Fields**
```js
Event: Strong Winds
Areas
Status
Severity
Certainty
Urgency
```

**Comment by Mloweedgar** [comment]
Suggested fields:
- [ ] Event
- [ ]  Headline
- [ ] Urgency
- [ ] Severity
- [ ] Certainty
- [ ] Areas
- [ ] Instructions
