### ISSUE TITLE
Remove unused components i.e resources, alert sources and e.t.c

### ISSUE THREAD

**Issue by BenMaruchu** [CodeTanzania/ewea-web#6]

**Comment by BenMaruchu** [comment]
Components that will remain are 
- [ ] Alerts(`api:alerts`) :warning: @Mloweedgar 
- [x] Action Catalog(`api:?`) - @BenMaruchu 
- [x] Action Taken(`api:?`) @BenMaruchu 
- [x] Function/ Emergency Functions i.e Evacuation(`api:incidenttypes*`) @mkumbobeaty 
- [x] Roles(`api:roles`) @navish 
- [x] Agencies(`api:parties`) @navish 
- [x] Focal People(`api:parties`) @navish 
- [x] Admin Boundaries(`api:features*`) @Mloweedgar - Remain as it is but need improments for other properties
- [x] Alert Types(`api:alerts*`) @mkumbobeaty 
- [ ] Dashboards :thinking: (`api:?`) @BenMaruchu @Mloweedgar @lykmapipo 
![IMAG1011](https://user-images.githubusercontent.com/7030859/65420401-be486c00-de09-11e9-9b50-ec90fe5f282b.jpg)

**Comment by lykmapipo** [comment]
![2019-09-23](https://user-images.githubusercontent.com/1610857/65435260-e85d5680-de28-11e9-9824-b11862463a3b.jpeg)
