### ISSUE TITLE
Improve action taken visualization

### ISSUE THREAD

**Issue by lykmapipo** [CodeTanzania/ewea-web#62]
![Screenshot from 2019-10-18 16-25-22](https://user-images.githubusercontent.com/1610857/67098084-2b121480-f1c4-11e9-8a2a-e1b3ad4a446f.png)

**Comment by lykmapipo** [comment]
![Screenshot from 2019-10-18 16-25-42](https://user-images.githubusercontent.com/1610857/67098109-38c79a00-f1c4-11e9-8b8c-23e2c4ad7b40.png)

**Comment by navish** [comment]
Closed in [#265 ](https://github.com/CodeTanzania/ewea-web/pull/265)
