### ISSUE TITLE
Should provide alert - action catalog (responsibilities)

### ISSUE THREAD

**Issue by lykmapipo** [CodeTanzania/ewea-web#7]
- [x] Prepare alert - action catalog @navish 
- [x] Provide simplified UI for recording action to be taken @BenMaruchu 
- [x] Provide simplified UI for questions to be prompted for feedback per each action @BenMaruchu

**Comment by navish** [comment]
Closed in [#223 ](https://github.com/CodeTanzania/ewea-web/pull/223) & [#227](https://github.com/CodeTanzania/ewea-web/pull/227) & [#229](https://github.com/CodeTanzania/ewea-web/pull/229)
